from __future__ import division, print_function
# from numpy.random import rand
from typing import Callable, Any
import cocoex
import cocopp
import os
import webbrowser

from CMA_ES import CMAES
# from MA_ES import MAES
# from IPOP_MA_ES import IPOP_MAES

# configuration
budget = 50000
count_evaluations = True
output_folder = "scipy-optimize-fmin"
# seeds generated by np.random.randint(0, high=2147483648, dtype=int)
seeds = [1887692902]


def f_min(function: Callable,
          x_initial: Any,
          seed: int):
    es = CMAES(function, x_initial, budget, count_evaluations, seed)
    # es = MAES(function, x_initial, budget, count_evaluations, seed)
    # es = IPOP_MAES(function, x_initial, budget, count_evaluations, seed)
    es.calculate()

    return es.best_value


def main():
    # coco functions
    suite_name = "bbob"
    suite = cocoex.Suite(suite_name, "", "")
    observer = cocoex.Observer(suite_name, "result_folder: " + output_folder)
    minimal_print = cocoex.utilities.MiniPrint()

    # testing
    for problem in suite:
        problem.observe_with(observer)
        x_init = problem.initial_solution
        f_min(problem, x_init, seeds[0])
        # x0 = problem.lower_bounds + ((rand(problem.dimension) + rand(problem.dimension)) *
        #                              (problem.upper_bounds - problem.lower_bounds) / 2)
        minimal_print(problem, final=problem.index == len(suite) - 1)

    # post-process data
    cocopp.main(observer.result_folder)
    webbrowser.open("file://" + os.getcwd() + "/ppdata/index.html")


main()