import copy
import numpy as np
import opfunu
from typing import Callable, Any

# from CMA_ES import CMAES
# from MA_ES import MAES
from IPOP_MA_ES import IPOP_MAES

# configuration
budget = 50000
count_evaluations = True
dimensions = [10, 20]
# seeds generated by np.random.randint(0, high=2147483648, size=30, dtype=int)
seeds = [1883015239, 2006242052, 1715379028, 1456948866, 1532066881, 1553370792,
          178657613,  777874201,  638331760,  672713588, 1409809928,  686928642,
           72580528,  130706632, 1149714668,  733480364, 1654794852, 1758053499,
         1241734102, 2071935836, 1344466298,  888888743,  813095853, 1056310373,
         1950118927, 1512615450,  266559572,  630364344,   76060793, 2139251363]

functions = opfunu.get_functions_based_classname("2021")
solutions = []
for i in range(len(functions)):
    solutions.append((functions[i].name, []))


def f_min(function: Callable,
          x_initial: Any,
          seed: int):
    # es = CMAES(function, x_initial, budget, count_evaluations, seed)
    # es = MAES(function, x_initial, budget, count_evaluations, seed)
    es = IPOP_MAES(function, x_initial, budget, count_evaluations, seed)
    es.calculate()

    return es.best_value


for dim in dimensions:
    for f, func in enumerate(functions):
        print(f"Calculating {func.name}...")

        for it in range(len(seeds)):
            print(f"Instance No. {it + 1}")
            f_copy = copy.deepcopy(func)
            fn = f_copy(ndim=dim)
            x_init = np.ones(dim)
            f_best = f_min(fn, x_init, seeds[it])
            solutions[f][1].append(f_best)

    print(f"\nSolutions for {dim}D:\n")
    print(solutions)
    print("")
